### PR TITLE
ipv6 support

### PR DESCRIPTION
**Pull request by orvitpng**
Implements support for:

- IPv6
- Happy Eyeballs

Sets the default to Happy Eyeballs.

### CODE REVIEW

**Comment by orvitpng** [comment]
@lpil what are your thoughts on Happy Eyeballs? trying to implement it, but I'm not sure if it should be the default as it does introduce a 250ms delay between IPv6 and IPv4 connections (as recommended by spec) meaning some people may have latency issues

**Comment by orvitpng** [comment]
This seems to break a few packages that use this, looks like some people directly write their ConnectionOptions. Not sure how to get around that or if it should be marked 2.0. From my testing, this works fine for regular usage, though maybe HappyEyeballs should be explicitly chosen.

**Review by lpil — COMMENTED** [review]
Thank you!

The name "happy eyeballs" is somewhat confusing. How about we call it "detect" and note that the happy eyeballs algorithm is used in the documentation.

Looking at the implementation here, doesn't it create an IPv4 connection even if the IPv6 has succeeded?

If both fail I believe that it hangs forever and never returns. Is that right?

It would be great to have some tests!

**Comment by orvitpng** [comment]
All fair points, it is obvious I didn't think through this enough. `Transparent` may be a better name. I'll send another commit through tomorrow.

**Comment by orvitpng** [comment]
I'm not particularly knowledgeable about how erlang handles processes, so a lot of this is uncharted territory, but to respond:

> The name "happy eyeballs" is somewhat confusing. How about we call it "detect" and note that the happy eyeballs algorithm is used in the documentation.

I've gone ahead and changed this to `Transparent`. It seems to be the most correct name that I can think up

> If both fail I believe that it hangs forever and never returns. Is that right?

No. If both fail, the second error is returned as far as I'm aware.

> Looking at the implementation here, doesn't it create an IPv4 connection even if the IPv6 has succeeded?

I'm not sure here, could you look at the current implementation and tell me if that is the case? These are my primary questions:

1. Should I be explicitly exiting these processes, or will they terminate automatically when the main function finishes?
2. Are there any potential issues with TCP connections that might prevent automatic process termination?
3. If the subject is never read for the second time, will the `process.send` operation hang?
4. Once the main process becomes the owner/controlling process of the second TCP connection, does that connection need to be manually closed, or will it be automatically handled when it's no longer used or referenced? This is assuming the first connection succeeded.

> It would be great to have some tests!

I've never really been known to dabble with unit tests, so I'm not sure what to add in that regard.

**Comment by lpil** [comment]
I feel the use of processes here makes the design somewhat more complex. Would it not be simpler to do it all using a single process? That way we don't need to send and receive messages or ensure that the processes are appropriately cleaned up.

**Pull request closed without merging**
